pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pulls the latest pushed code from GitHub
                checkout scm
            }
        }

        stage('Deploy / Restart Container') {
            steps {
                sh '''
                    # If package.json or Dockerfile changed, rebuilds. Otherwise, just restarts or applies changes.
                    docker compose up -d --build
                '''
            }
        }
    }
    
    post {
        success {
            echo 'Changes deployed successfully! Refresh your browser or watch live changes.'
        }
    }
}
