pipeline {
    agent any
    stages {
        //stage('Checkout') {
           // steps {
                // Automatically checks out your repository using Git SCM
                // (Replace branch name if yours is 'main' or something else)
             //   checkout([
           //         $class: 'GitSCM', 
         //           branches: [[name: '*/master']], 
       //             userRemoteConfigs: [[url: 'https://github.com/your-username/your-repo.git']]
     //           ])
   //         }
 //       }
 
        stage('Stage1:Run Shell script 1') {
            steps {
                // Execute your shell script (assumes your script file is named script.sh)
		sh 'cd Shell-Scripts && ./firstscript.sh'
                
                // OR run inline commands directly:
                // sh 'echo "Running commands from my git repo!"'
            }
        }
        stage('Stage2:Run Shell script 2') {
	   steps {
		sh 'cd Shell-Scripts && ./secondscript.sh'
           }
        } 
    }
}
