pipeline {
    agent any
    stages {
        stage('Stage1:Run Shell script 1') {
            steps {
                // Execute your shell script (assumes your script file is named script.sh)
		sh 'cd Shell-Scripts && ./firstscript.sh'
                
                // OR run inline commands directly:
                // sh 'echo "Running commands from my git repo!"'
            }
        }
        stage('Stage2:Run Shell script 2') {
	   steps {
		sh 'cd Shell-Scripts && ./secondscript.sh'
           }
        }

        stage('Stage3:Run Shell script 3') {
	  steps {
		sh 'cd Shell-Scripts && ./thirdscript.sh'
          }
        }
	stage('Stage4:Run Shell script 4') {
	  steps {
	       sh 'cd Shell-Scripts && ./fourthscript.sh 1 10'
	  }
	} 
    }
}

